build:
  stage: build
  script:
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DTEST_DATA_PATH=/mnt/public/poker/data/ ..
    - make all

test:
  stage: test
  script: cd build && make check
